### ISSUE TITLE
Починить main_handler

### ISSUE THREAD

**Issue by gazkhul** [Studio-Yandex-Practicum/rehabilitation_bot#18]
Нет возможности тестировать приложение, выпадает с ошибкой:

    Traceback (most recent call last):
      File "/home/user/dev/yandex/rehabilitation_bot/src/application.py", line 4, in <module>
        from bot.handlers import main_handler
      File "/home/user/dev/yandex/rehabilitation_bot/src/bot/handlers.py", line 17, in <module>
        CallbackQueryHandler(
    TypeError: CallbackQueryHandler.__init__() missing 1 required positional argument: 'callback'

**Comment by Yana-Denisova** [comment]
В main_handler криво поставили заглушку, я исправила, можно тестировать.
